### ISSUE TITLE
Framework und weitere Technologien auswählen

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/elegia#2]
Auswahl von dem benutzten Framework

**Comment by rodchenk** [comment]
Zur Auswahl haben wir folgende Frameworks:

- Laravel
- CakePHP
- Symphony

Alle sind ziemlich gleich, wir muss nur entscheiden, mit welchem wir zur Recht kommen würden. Ansonsten verwenden wir den Standardpaket:

- JS (jQuery + ajax)
- CSS (Bootstrap)
- DB (mySQL + json-Dateien)
- externe API (etwas von Google, damit wir cool sind)

**Comment by nguythin** [comment]
wir müssen einen Framework benutzen, und egal Laravel oder CakePHP oder Symphonym. Aber meiner Meinung nach sollten wir Laravel benutzen, obwohl ich bis jetzt noch keine Ahnung darüber, aber es gibt mehrere Möglichkeit im Internet zu lernen als CakePHP oder Symphony

**Comment by rodchenk** [comment]
ja, dann bleiben wir auf laravel

**Comment by rodchenk** [comment]
endgültige Entscheidung ist CakePHP
