### ISSUE TITLE
Entwicklungsumgebung und Richtlinien

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/elegia#3]
Das ist mein Vorschlag zur Einstellung von Entwicklungsumgebung und das Vorgehen zur sauberen Entwicklung und Versionierung. Bitte durchlesen und falls es Fragen gibt, gerne helfe ich euch.

**Comment by rodchenk** [comment]
Wir haben einen **[Releaseserver](http://fbwframework.th-brandenburg.de/~fw11)** und jeder sollte einen **Entwicklungsserver** local haben. 
1. Ich benutze dafür [XAMPP](https://www.apachefriends.org/download.html). Ihr könnt das Programm herunterladen und local an ihren Rechnern installieren. Dann muss noch **[Git](https://git-scm.com/download/win)** local installiert werden. 
2. Nachdem alles fehlerfrei installiert ist, checkt ob alles funktioniert. Dafür _xampp/xampp_start.exe_ starten, im Browser als URL localhost eingeben und auf die Seite gehen. 
3. Nachdem alles gecheckt ist, geht in _xammp/htdocs/_ Verzeichnis. Den Inhalt braucht man nicht mehr und der muss gelöscht werden.  Dann ein Maus Rechtsklick und **Git Bash Here**. In der Console sollen die folgenden Befehle ausgeführt werden:

- git config --global user.name "DEIN_NAME"
- git config --global user.email "DEIN_EMAIL"
- git clone https://github.com/rodchenk/elegia.git
- git init
- git add --all
- git commit . -m "init commit"

4. Jetzt habt ihr das Projekt von github heruntergeladt. Dieses Projekt habe ich aus fbwframework commitet und es wird local nicht funktionieren. Ich werde in den nächsten Tagen das Projekt in github neu initialisieren und konfigurieren, danach gebe ich euch Bescheid und ihr führt in Git Console in Projektverzeichnis ( _xammp/htdocs/_) folgenden Befehr aus:

- git pull https://github.com/rodchenk/elegia master force

5. Mit diesem Befehl haben sie immer den aktuellen Stand. Das heisst wir laden initial das Projekt auf github hoch, dann jeder lädt es herunter, kann die Dateien bearbeiten und wenn der/diejenige feretig ist, muss er/sie die Aenderungen commiten (auf github hochladen).  Das macht man mit folgendem Befehl:

- git commit . -m "irgendein eindeutiger Kommentar"
- git push https://github.com/rodchenk/elegia master

6. Ein mal pro Woche werden wir das Projekt auf Releaseserver (fbwframework) hochladen, das wird auch durch git console durchgeführt. Falls ihr noch keine Erfahrung mit GIT habt, sollt ihr euch nicht erschrecken, Git macht das Leben einfacher und wir können unser Projekt versionieren und falls etwas schief geht, können wir auf vorherige Versionen springen.

Das Vorgehen bei git ist so:

- git init -> Initialisierung von Workarea, nun wir das Git diese Verzeichnis auf Aenderungen pruefen.
- git add --all -> alle neue Dateien muessen zur lokalen Git hinzigefuegt werden, damit er weisst, was er zu pruefen hat.
- git status -> zeigt ob etwas geaendert wurde oder ob es nicht hinzugefuegte Dateien gibt
- git log -> zeigt die letzten Commits und Kommentare.
- git commit -m "your comment" -> locales speichern der aktuellen Version mit ihrem Kommentar
- git push https://github.com/rodchenk/elegia master -> hochladen auf Versionierungsserver (github.com) in Master branch. 

Das Syntax in Git-Console ist wie in Linux-Systemen, damit kennt ihr euch schon aus.

**Comment by nguythin** [comment]
Ich habe auch schon XAMMP in meinem Laptop. Deswegen habe ich eine Frage. Du hast gesagt dass alle Verzeichnis (bedeutet Dateien) in htdoc gelöscht werden müssen. Aber ich habe 2 Webseite mit XAMMP erstellt. wenn ich alle lösche, werde ich meine alte Dateien verlieren. Kannst du mir erklären, warum ich alles löschen muss? Danke

**Comment by rodchenk** [comment]
@nguythin  alles löschen muss man, wenn man xampp **erst instaliert** hat, dann gibt es in diesem Verzeichnis alle Standardsachen von xampp. Aber wenn du schon etwas entwickelt hast, dann brauchst du nichts löschen.

**Comment by rodchenk** [comment]
kurz mal zur Info: **wir sind auf CakePHP umgestiegen**, da es bei Laravel auf dem fbwframework diverse Probleme gibt. Ihr könnt schon das Projekt auschecken (herunterladen).
wenn Folder htdocs leer ist, geht ihr da rein, macht die Git console auf und tippt foldendes:

- git init .
- git remote add origin https://github.com/rodchenk/elegia.git
- git fetch origin
- git checkout master

unter **localhost/elegia-web** ist dann das Projekt und
unter **localhost/docs** ist die Wbseite mit Präsentation

Ich habe bei mir lokal alles getestet, Datenbank und Entitäten erstellt, so jetzt kann richtig gearbeitet werden. Wenn oben geschriebene Schritte erfolgreich durch gemacht sind, dann könnt ihr folgendes in root von eurem Projekt (htdocs oder so was, da wo ihr **git init .** gemacht habt) machen:

### Projekt auschecken 

- git status (es muss **nothing to commit, working tree clean** zeigen)
- git pull origin (es wird die neuen Sachen in ihr Root herunterladen)

### Script zum Laden der Datenbank
dann habe ich ein Script geschrieben um die Datenbank rein zu laden, es befindet sich im root und heisst **db-import.bat**. Unter Windows könnt ihr es einfach ausführen, dann wird ihr nach Password gefragt, by Default ist es LEER, dann einfach ENTER klicken, eventuell noch ein mal ENTER klicken und dann paar Sekunden warten bis es geladen wird. Beachtet die Meldungen in der Console. falls etwas nicht klappt, einfach fragen.

### Test

Wenn alles erfolgreich durchgelaufen ist, kann man unter z.B. **localhost/elegia-web/user** die Seite anschauen

**Comment by rodchenk** [comment]
### Aktueller Stand

Um auf dem aktuellen Stand zu bleiben, macht führt bitte folgendes paar mal in Woche aus:

**`$ git pull origin `**
