### ISSUE TITLE
Logo Skizze

### ISSUE THREAD

**Issue by nickinko** [rodchenk/elegia#4]

**Comment by NickIvachshenko** [comment]
![output_lxknwj](https://user-images.githubusercontent.com/32674066/48574158-baf17380-e90e-11e8-909d-35ac03e53d3a.gif)
![new project](https://user-images.githubusercontent.com/32674066/48574161-c04ebe00-e90e-11e8-8341-0c686c221582.png)

**Comment by rodchenk** [comment]
![logos](https://pp.userapi.com/c845017/v845017948/139370/LchIt8yZ17M.jpg)

**Comment by rodchenk** [comment]
ich bin für oben rechts und unten links. und ihr? @NickIvachshenko  @nguythin

**Comment by rodchenk** [comment]
scheisse, elegia schreibt man mit **e** statt **i**

**Comment by rodchenk** [comment]
**korrigiert**
![logos](https://pp.userapi.com/c849528/v849528948/b06e8/ab4iR6wTyMU.jpg)

**Comment by nguythin** [comment]
Ich habe eine Frage, was Elegia bedeutet? Warum sollten wir unsere Webseite Elegia nennen?

**Comment by nguythin** [comment]
einverstanden mit dem oben recht
