### ISSUE TITLE
DB-Schema und ER-Diagramm

### ISSUE THREAD

**Issue by nickinko** [rodchenk/elegia#5]
Erstellt mit:
https://erdplus.com/
STANDALONE
###

**Comment by nickinko** [comment]
![erdplus-diagram](https://user-images.githubusercontent.com/32674066/48576091-eb87dc00-e913-11e8-8c6a-bb4e9b05ce89.png)

**Comment by nguythin** [comment]
Für die Beziehung zwischen Kunde und Verkäufer denke ich, dass ein Verkäufer keinen oder mehrere Kunden kontaktieren kann und umgekehrt ein Kunde keinen oder mehrere Verkäufer kontaktieren kann. Außerdem kann ein Verkäufer keine Ware verkaufen (in diesem Fall hat er schon angemeldet aber noch nicht etwas verkaufen) und ggf. ein Kunde kann auch keine Waren kaufen. Das bedeutet, die Beziehung zwischen Kunden oder Verkäufer und Waren ist (0,n)

**Comment by nickinko** [comment]
[ER_diagram.zip](https://github.com/rodchenk/elegia/files/2604293/ER_diagram.zip)

**Comment by nguythin** [comment]
![erdplus-diagram](https://user-images.githubusercontent.com/29575916/48872893-79b80280-edeb-11e8-8970-ac51a11b0a9f.png)

**Comment by nguythin** [comment]
[untitled (2).zip](https://github.com/rodchenk/elegia/files/2610434/untitled.2.zip)

**Comment by nguythin** [comment]
![erdplus-diagram 1](https://user-images.githubusercontent.com/29575916/48939824-d0216000-ef15-11e8-8372-6e4db71c09b0.png)

**Comment by rodchenk** [comment]
@nguythin das sieht gut aus. Aber wir stellen jetzt uns die Frage -> wer muss sich registrieren? Nur Lieferant, nur Kunde, beide oder keine? Ich würde entweder wie bei Lieferando machen (nur Lieferant erstellt das Konto) oder beide registrieren (**ich bin eher dafür**).

**Comment by rodchenk** [comment]
und vielleicht machen wir noch das Prozessablauf vom Bestellen bis zur Empfang der Bestellung, damit wir sicher sein können, welche Entitäten und Beziehungen notwendig sind. Beispielsweise die Beziehung {Unternehmen [liefert] Bestellung} ist mir unklar, da ich mir nicht vorstellen kann, was da abgebildet werden kann.

**Comment by nguythin** [comment]
Bevor ich auf deine Frage antworte, sollten wir uns entscheiden, wer Kunde ist. Wenn unsere Kunden nur Unternehmen sind, deren Bestellung für Mitarbeiter ist, sollten beide registrieren. Wenn alle Benutzer Kunden sein können, sollten wir wie Lieferando machen, das bedeutet nur Lieferant registrieren.
Wenn ein Kunde bestellt, wird diese Bestellung zum Lieferant kommt und er muss die Bestellung vom Kunden liefert. 
Ich habe auch die Idee von Lieferando benutzt, um das ER-Diagramm zu erstellen.

**Comment by nguythin** [comment]
@rodchenk

**Comment by rodchenk** [comment]
@nguythin  wir haben jetzt dein Diagramm ein bisschen erweitert, sodass jetzt alles logisch ganz gut passt. 
Das ist [hier](https://www.draw.io/#Hrodchenk%2Felegia%2Fmaster%2Felegia.xml) zu sehen. Wir haben noch paar Test-cases gemacht und alles ist perfekt abgelaufen. Die Applikation wurde für Firmen gedacht, so jetzt müssen beide Seiten registrieren.

**Comment by rodchenk** [comment]
![elegia](https://raw.githubusercontent.com/rodchenk/elegia/master/docs/elegia.png)

**Comment by rodchenk** [comment]
ich würde auf rot markierte sachen verzichten, das ich einfacher, fehlerfrei und gehört eigentlich zur Lieferantenseite
![elegia](https://raw.githubusercontent.com/rodchenk/elegia/master/docs/elegia2.png)

**Comment by nguythin** [comment]
Aber ich habe eine Frage, wie man weiß, die Bestellung schon geliefert ist. Ich denke, der Lieferant muss Bescheid geben. Das bedeutet, wir eine Relation zwischen der Bestellung (oder Korb) und dem Lieferant erstellen

**Comment by nguythin** [comment]
Nach der Lieferung muss der Lieferant die Lieferstatus aktualisieren

**Comment by rodchenk** [comment]
es gibt eine Entität Lieferstatus ({'in bearbeitung', 'in zustellung', 'zugestellt'}) und Beziehung [hat Lieferstatus] mit Attributen id_status und id_korb

**Comment by nguythin** [comment]
ich habe gesehen, aber es gibt keine Relation zwischen Lieferanten und Lieferstatus, sondern nur ein Relation zwischen Korb und Lieferstatus

**Comment by nguythin** [comment]
denn eigentlich muss der Lieferant den Status "geliefert" auffühlen, oder?

**Comment by nickinko** [comment]
Es wird automatisch ausgefühlt werden.
in bearbeitung = 0 bis 1 Stunde
in zustellung = 1 bis 24 Stunden
zugestellt = nach 24 Stunden
Falls nicht zugestellt, dan Kunde/Lieferant ruft die Hotline, aber es ist nicht in Tabelle zu zeigen =)

**Comment by rodchenk** [comment]
es muss keine direkte Beziehung zwischen Lieferanten und Lieferstatus geben. Lieferant sieht alle bei ihm bestellte "Körbe" und kann direkt den Lieferstatus eingeben.

**Comment by rodchenk** [comment]
das ist doch nur logische Beziehung, keine echte Beziehung. Ansonsten wären die Daten redundant abgebildet

**Comment by nguythin** [comment]
Das bedeutet, Kunde muss vor einem Tag bestellen, oder?

**Comment by rodchenk** [comment]
nein, warum? wir haben keine automatische Ausfüllung, wie Nick geschrieben hat. alles ist logisch verbunden. was würdest du in der beziehung zwischen lieferanten und lieferstatus abbilden?

**Comment by nickinko** [comment]
![er](https://user-images.githubusercontent.com/32674066/49601701-da684300-f986-11e8-853a-3e58643a4a07.jpg)
![tables](https://user-images.githubusercontent.com/32674066/49601702-db00d980-f986-11e8-8c4a-8d2b353b7a5a.jpg)
