### ISSUE TITLE
Framework auf dem THB-Server testen

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/elegia#7]
falls Laravel nicht geht, müssten wir schnell auf CakePHP umsteigen. Bitte testen und Bescheid geben @NickIvachshenko

**Comment by nickinko** [comment]
Laravel **version 5.5** , da server auf PHP 7.0.22 läuft.
1. Go "fbwframework.th-brandenburg.de" mit putty
2. from your default **fwXX** go to **public_html** directory (**cd public_html**)
3. now type  **composer create-project laravel/laravel elegia_DEINENAME "5.5.*"**

![12345](https://user-images.githubusercontent.com/32674066/49463074-dc4fcc00-f7f7-11e8-8655-bd09dbe1716f.jpg)

**Comment by nickinko** [comment]
![fail](https://user-images.githubusercontent.com/32674066/49464627-b62c2b00-f7fb-11e8-95ce-58299e2b866e.jpg)

**Comment by rodchenk** [comment]
es sollte eigentlich einfach mit **/~fw10/**

**Comment by nguythin** [comment]
Entschuldigung,ich kann nicht arbeiten
![unbenannt](https://user-images.githubusercontent.com/29575916/49519151-a1ee3980-f8a0-11e8-9ded-4de1c306df58.png)
Könnt ihr mir helfe?

**Comment by nguythin** [comment]
bei mir läuft gut

**Comment by rodchenk** [comment]
kurz mal zur Info: **wir sind auf CakePHP umgestiegen**, da es bei Laravel auf dem fbwframework diverse Probleme gibt. Ihr könnt schon das Projekt auschecken (herunterladen).
wenn Folder htdocs leer ist, geht ihr da rein, macht die Git console auf und tippt foldendes:

- git init .
- git remote add origin https://github.com/rodchenk/elegia.git
- git fetch origin
- git checkout master

unter **localhost/elegia-web** ist dann das Projekt und
unter **localhost/docs** ist die Wbseite mit Präsentation

**Comment by rodchenk** [comment]
Ich habe bei mir lokal alles getestet, Datenbank und Entitäten erstellt, so jetzt kann richtig gearbeitet werden. Wenn oben geschriebene Schritte erfolgreich durch gemacht sind, dann könnt ihr folgendes in root von eurem Projekt (htdocs oder so was, da wo ihr **git init .** gemacht habt) machen:

### Projekt auschecken 

- git status (es muss **nothing to commit, working tree clean** zeigen)
- git pull origin (es wird die neuen Sachen in ihr Root herunterladen)

### Script zum Laden der Datenbank
dann habe ich ein Script geschrieben um die Datenbank rein zu laden, es befindet sich im root und heisst **db-import.bat**. Unter Windows könnt ihr es einfach ausführen, dann wird ihr nach Password gefragt, by Default ist es LEER, dann einfach ENTER klicken, eventuell noch ein mal ENTER klicken und dann paar Sekunden warten bis es geladen wird. Beachtet die Meldungen in der Console. falls etwas nicht klappt, einfach fragen.

### Test

Wenn alles erfolgreich durchgelaufen ist, kann man unter z.B. **localhost/elegia-web/user** die Seite anschauen

**Comment by rodchenk** [comment]
### paar Punkte noch:

composer muss installiert werden indem ihr den Befehl **php composer.phar install** ausführt. Dafür muss **php** als environment variable gesetzt werden. Composer muss in Projekt-Ordner isntalliert werden (in /elegia-web). Dann unter /elegia-web/config/app.php müsst ihr folgendes ändern:
![image](https://user-images.githubusercontent.com/30366483/49690034-8a29e600-fb2a-11e8-9070-ff5adb4a6b2d.png) 
Und am besten erst jetzt den oben genannten Script zum Laden der Datenbank ausführen.

**Comment by rodchenk** [comment]
### **Erledigt**
